apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-flow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-flow-app
  template:
    metadata:
      labels:
        app: event-flow-app
    spec:
      containers:
        - name: event-flow-app
          image: 509399632114.dkr.ecr.us-east-1.amazonaws.com/event-flow-app:5
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
